print('Podaj pierwszą liczbę do dodania:')
first = input()
print('Podaj drugą liczbę do dodania:')
second = input()
print('Podaj trzecią liczbę do dodania:')
third = input()
print('Suma wynosi ' + first + second + third)